esp32:
  variant: ESP32C5
  board: esp32-c5-devkitc-1
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_SOC_WIFI_HE_SUPPORT: y
      CONFIG_ESP_WIFI_11AX_SUPPORT: y
      CONFIG_SOC_WIFI_SUPPORT_5G: y

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

logger:
  level: DEBUG
  baud_rate: 115200
  hardware_uart: USB_SERIAL_JTAG

api:
  encryption:
    key: ${api_key}
  reboot_timeout: 15min

ota:
  - platform: esphome
    password: ${ota_password}
    version: 2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .local
  use_address: ${device_name}.local
  power_save_mode: NONE
  fast_connect: true
  enable_on_boot: true
  reboot_timeout: 10min
  # band: "5GHz"   # uncomment to force 5 GHz only
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_captive
    ap_timeout: 120s
  on_disconnect:
    then:
      - lambda: |-
          id(_wifi_disconnects_since_boot)++;

captive_portal:

mdns:

# GPIO27 = USER LED (yellow) — solid ON when API connected, blinks when not
status_led:
  pin:
    number: GPIO27

esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    active: true
    interval: 320ms
    window: 90ms
    continuous: true

bluetooth_proxy:
  active: true

select:
  - platform: template
    name: "BLE Scan Profile"
    id: sel_ble_scan_profile
    optimistic: true
    restore_value: true
    initial_option: "Medium"
    options:
      - "Low"
      - "Medium"
      - "High"
    set_action:
      - lambda: |-
          id(ble_tracker).stop_scan();
          auto opt = id(sel_ble_scan_profile).current_option();
          if (opt == "Low") {
            id(ble_tracker).set_scan_interval(320);
            id(ble_tracker).set_scan_window(30);
          } else if (opt == "Medium") {
            id(ble_tracker).set_scan_interval(320);
            id(ble_tracker).set_scan_window(90);
          } else {
            id(ble_tracker).set_scan_interval(320);
            id(ble_tracker).set_scan_window(160);
          }
          id(ble_tracker).start_scan();

sensor:
  - platform: internal_temperature
    name: "Internal Temp"
    entity_category: diagnostic

  - platform: uptime
    name: "Uptime"
    unit_of_measurement: "h"
    accuracy_decimals: 2
    update_interval: 60s
    filters:
      - lambda: return x / 3600.0;
    entity_category: diagnostic

  - platform: wifi_signal
    id: wifi_signal_dbm
    name: "Wi-Fi RSSI"
    update_interval: 30s
    entity_category: diagnostic

  - platform: template
    name: "Wi-Fi Disconnects (since boot)"
    id: wifi_disconnects_since_boot_sensor
    entity_category: diagnostic
    accuracy_decimals: 0
    update_interval: 30s
    lambda: |-
      return id(_wifi_disconnects_since_boot);

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
      entity_category: diagnostic
    mac_address:
      name: "MAC"
      entity_category: diagnostic
    ssid:
      name: "SSID"
      entity_category: diagnostic
    bssid:
      name: "BSSID"
      entity_category: diagnostic

button:
  - platform: restart
    name: "Restart Device"

globals:
  - id: _wifi_disconnects_since_boot
    type: int
    restore_value: no
    initial_value: '0'

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
