esp32:
  variant: esp32c6
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_SOC_WIFI_HE_SUPPORT: y   # Future Wi-Fi 6 Support
      CONFIG_ESP_WIFI_11AX_SUPPORT: y # Future Wi-Fi 6 Support

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: -10
    then:
      # Enable external antenna by default (FM8625H RF switch)
      - output.turn_off: ant_gpio3     # LOW -> RF switch power ON
      - output.turn_on:  ant_gpio14    # HIGH -> external antenna (U.FL)

logger:
  level: DEBUG
  baud_rate: 115200
  hardware_uart: USB_SERIAL_JTAG

api:
  encryption:
    key: ${api_key}
  reboot_timeout: 15min

 ota:
  - platform: esphome
    password: ${ota_password}
    version: 2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .local
  use_address: ${device_name}.local
  power_save_mode: NONE
  fast_connect: true
  enable_on_boot: true
  reboot_timeout: 10min
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_captive
    ap_timeout: 120s

captive_portal:

mdns:

# Status LED behavior: Solid = all OK, slow blink = Wi-Fi but no API client, fast blink = no Wi-Fi
status_led:
  pin:
    number: GPIO15

# External antenna control (GPIO3 power, GPIO14 select - FM8625H RF switch)
output:
  - platform: gpio
    id: ant_gpio3
    pin: GPIO3

  - platform: gpio
    id: ant_gpio14
    pin: GPIO14

# BLE scanning and Bluetooth proxy for Home Assistant
esp32_ble_tracker:
  scan_parameters:
    active: true
    interval: 211ms
    window: 180ms
    continuous: true

bluetooth_proxy:
  active: true

# Text sensors for Wi-Fi info
text_sensor:
  - platform: wifi_info
    bssid:
      name: "BSSID"
      entity_category: diagnostic
    ip_address:
      name: "IP"
      entity_category: diagnostic

# Switches
switch:
  # External antenna selector (FM8625H RF switch control)
  - platform: template
    name: "External Antenna"
    optimistic: true
    restore_mode: ALWAYS_ON
    turn_on_action:
      - output.turn_off: ant_gpio3     # LOW -> RF switch power ON
      - output.turn_on:  ant_gpio14    # HIGH -> external antenna (U.FL/RF2)
    turn_off_action:
      - output.turn_off: ant_gpio3     # LOW -> RF switch power ON
      - output.turn_off: ant_gpio14    # LOW -> internal antenna (PCB/RF1)

# Diagnostics and basics
sensor:
  - platform: uptime
    name: "Uptime"
    unit_of_measurement: "h"
    accuracy_decimals: 2
    update_interval: 60s
    filters:
      - lambda: return x / 3600.0;

  - platform: internal_temperature
    name: "Internal Temp"
    entity_category: diagnostic

  - platform: wifi_signal
    name: "Wi-Fi Signal"
    update_interval: 30s
    entity_category: diagnostic

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
