esp32:
    variant: esp32c6
    board: seeed_xiao_esp32c6
    framework:
        type: esp-idf
        sdkconfig_options:
            CONFIG_SOC_WIFI_HE_SUPPORT: y
            CONFIG_ESP_WIFI_11AX_SUPPORT: y

esphome:
    name: ${device_name}
    friendly_name: ${friendly_name}
    on_boot:
        priority: -10
        then:
            # Enable external antenna by default (FM8625H RF switch)
            - output.turn_off: ant_gpio3     # LOW -> RF switch power ON
            - output.turn_on:  ant_gpio14    # HIGH -> external antenna (U.FL)

logger:
    level: DEBUG
    baud_rate: 115200
    hardware_uart: USB_SERIAL_JTAG

api:
    encryption:
        key: ${api_key}
    reboot_timeout: 15min

ota:
    - platform: esphome
      password: ${ota_password}
      version: 2

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
    domain: .local
    use_address: ${device_name}.local
    power_save_mode: NONE
    fast_connect: true
    enable_on_boot: true
    reboot_timeout: 10min
    ap:
        ssid: "${friendly_name} Fallback"
        password: !secret wifi_captive
        ap_timeout: 120s
    on_disconnect:
        then:
            - lambda: |-
                id(_wifi_disconnects_since_boot)++;

captive_portal:

mdns:

# Status LED on Seeed XIAO ESP32-C6 (GPIO15, not inverted to match your working config)
status_led:
    pin:
        number: GPIO15

# External antenna control (GPIO3 power, GPIO14 select - FM8625H RF switch)
output:
    - platform: gpio
      id: ant_gpio3
      pin: GPIO3

    - platform: gpio
      id: ant_gpio14
      pin: GPIO14

# ===== BLE & Bluetooth Proxy =====
# Default Aggressive (100% duty cycle); user selection persists across reboots
esp32_ble_tracker:
    id: ble_tracker
    scan_parameters:
        active: true
        interval: 160ms
        window: 160ms
        continuous: true

bluetooth_proxy:
    active: true

# Selector to switch only between Aggressive and Balanced
select:
    - platform: template
      name: "BLE Scan Profile"
      id: sel_ble_scan_profile
      optimistic: true
      restore_value: true
      initial_option: "Aggressive"
      options:
          - "Aggressive"
          - "Balanced"
      set_action:
          - lambda: |-
                auto opt = id(sel_ble_scan_profile).current_option();
                if (opt == "Aggressive") {
                    id(ble_tracker).set_scan_interval(160);
                    id(ble_tracker).set_scan_window(160);
                    id(ble_tracker).set_scan_active(true);
                } else {
                    id(ble_tracker).set_scan_interval(320);
                    id(ble_tracker).set_scan_window(160);
                    id(ble_tracker).set_scan_active(true);
                }

# Text sensors
text_sensor:
    - platform: wifi_info
      bssid:
          name: "BSSID"
          entity_category: diagnostic
      ip_address:
          name: "IP"
          entity_category: diagnostic
      ssid:
          name: "SSID"
          entity_category: diagnostic
      mac_address:
          name: "MAC"
          entity_category: diagnostic

# Switches
switch:
    - platform: template
      name: "External Antenna"
      optimistic: true
      restore_mode: ALWAYS_ON
      turn_on_action:
          - output.turn_off: ant_gpio3     # LOW -> RF switch power ON
          - output.turn_on:  ant_gpio14    # HIGH -> external antenna (U.FL/RF2)
      turn_off_action:
          - output.turn_off: ant_gpio3     # LOW -> RF switch power ON
          - output.turn_off: ant_gpio14    # LOW -> internal antenna (PCB/RF1)

# Buttons
button:
    - platform: restart
      name: "Restart Device"

# Basics + Wi‑Fi disconnect count (since boot)
sensor:
    - platform: uptime
      name: "Uptime"
      unit_of_measurement: "h"
      accuracy_decimals: 2
      update_interval: 60s
      filters:
          - lambda: return x / 3600.0;

    - platform: internal_temperature
      name: "Internal Temp"
      entity_category: diagnostic

    - platform: wifi_signal
      id: wifi_signal_dbm
      name: "Wi‑Fi RSSI"
      update_interval: 30s
      entity_category: diagnostic

    - platform: template
      name: "Wi‑Fi Disconnects (since boot)"
      id: wifi_disconnects_since_boot_sensor
      entity_category: diagnostic
      accuracy_decimals: 0
      update_interval: 30s
      lambda: |-
          return id(_wifi_disconnects_since_boot);

# Globals (since-boot only; not restored)
globals:
    - id: _wifi_disconnects_since_boot
      type: int
      restore_value: no
      initial_value: '0'

time:
    - platform: sntp
      id: sntp_time
      servers:
          - 0.pool.ntp.org
          - 1.pool.ntp.org
